### ISSUE TITLE
image links return 404

### ISSUE THREAD

**Issue by scottdangelo** [IBM/pixiedust-facebook-analysis#43] opened 2018-03-07 16:52 UTC
In the cell for Visual Recognition to classify thumbnail images, there are 2 bad links:
```

Skipping url http://www.ibm.com/watson/assets/img/cloud/hero_cloud.jpg: Error: Unknown error, Code: 400
Skipping url http://www-03.ibm.com/press/img/ibmpos_blu_feed.jpg: Error: Unknown error, Code: 400
```
These look to be bad from the IBM web URLs, so I don't think there is much that can be done in the notebook.

**Comment by markstur** [comment] 2018-03-07 17:39
Yes.  "Skipping url" was added to deal with these exceptions and there is another issue #33 to make this look cleaner eventually.

**Comment by stevemart** [comment] 2018-04-10 13:49
Closing as a dupe of #33

**Closed by stevemart** 2018-04-10 13:49 UTC
